---

- name: upload Enable Registry Auditing script
  win_template:
    src: EnableRegistryAudit.ps1.j2
    dest: "{{ win_temp_dir }}\\EnableRegistryAudit.ps1"

- name: Enable Registry auditing for selected paths
  win_shell: "Powershell -Exec Bypass -File \"{{ win_temp_dir }}\\EnableRegistryAudit.ps1\" \"{{ item }}\""
  with_items: "{{ win_audit_regpaths }}"
  register: setacl_results
- debug: var=setacl_results
